campusnutrition/apps/restaurants/urls.py
from django.urls import path

from . import views
from . import utils
from .views import *

urlpatterns = [
    path('restaurant_list/', RestaurantList.as_view(), name = 'listing'),
    path('',                       views.redirect_view),
    path('about/',                 views.about,     name='about'),
    path('contact/',               views.contact,   name='contact'),
    path('subscribe/',             views.subscribe, name='subscribe'),
    path('<str:area>/map/',        views.map,       name='map'),
    path('<str:area>/map/getJSON', utils.getGeoJSON, name='mapGetJSON'),
    path('<str:area>/',            views.home,      name='home'),
    path('ajax/name/', getname, name = 'get_names'),
    path('ajax/category/', getcategory, name = 'get_categories'),
    path('<str:area>/<str:name>/', views.food,      name='food'),
]

campusnutrition/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('campusnutrition.apps.restaurants.urls')),
]

campusnutrition/apps/restaurants/models.py
from django.db    import models
from django.utils import timezone

# Restaurant model
class Restaurant(models.Model):
    # Area restaurants correspond to
    area     = models.CharField(max_length=256)

    # Name of the restaurant
    name     = models.CharField(max_length=256)

    # Category of the restaurant. Specific categories
    # are comma-separated
    category = models.CharField(max_length=256)

    # Filename of the restaurant image. placeholder.png
    # if none exists
    img      = models.CharField(max_length=256)

    # Address of the restaurant
    # req: abide by the national postal service of the country concerned
    address  = models.CharField(max_length=256)

    # Latitude of the restaurant
    # req: valid within -90 and +90, up to 6 decimal places
    lat      = models.DecimalField(max_digits=8, decimal_places=6)

    # Longitude of the restaurant
    # req: valid within -180 and +180, up to 6 decimal places
    lng      = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return self.name

class Restaurant_Foods(models.Model):
    # Area restaurants correspond too
    area      = models.CharField(max_length=256)

    # Name of the restaurant
    name      = models.CharField(max_length=256)
    
    # Filename of the image of the food
    img       = models.CharField(max_length=256)

    #n Name of food
    food       = models.CharField(max_length=256)

    # Calories of food
    calories   = models.CharField(max_length=256)

    # Category of food (ex.vegan, vege, meat...)
    category   = models.CharField(max_length=256)

    # info of food
    info1      = models.CharField(max_length=256)

    # info of food
    info2      = models.CharField(max_length=256)

    # info inside modal popup
    modal_Info = models.CharField(max_length=256)

    def __str__(self):
        return self.name

campusnutrition/apps/restaurants/forms.py
from django import forms

class ContactForm(forms.Form):
    name       = forms.CharField(required=True)
    from_email = forms.EmailField(required=True)
    subject    = forms.CharField(required=True)
    message    = forms.CharField(widget=forms.Textarea, required=True)

campusnutrition/apps/restaurants/views.py
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from django.conf import settings

from rest_framework.generics import ListAPIView

from .utils import getGeoJSON
from .forms  import ContactForm
from .models import Restaurant, Restaurant_Foods
from .utils  import SendSubscribeMail, send_contact_email, util_render
from .serializers import restaurantSerializers
from .pagination import StandardResultsSetPagination

# Currently redirect to ubc area
def redirect_view(request):
    response = redirect("/ubc/")
    return response

# Home view for the given area
def home(request, area):
    restaurant_list = Restaurant.objects.filter(area=area)
    context = {
        'restaurant_list': restaurant_list
    }
    return util_render(request, 'restaurants/home.html', context)

class RestaurantList(ListAPIView):
        serializer_class = restaurantSerializers

        def get_queryset(self):
            queryList = Restaurant.objects.all()
            
            name = self.request.query_params.get('name', None)
            category = self.request.query_params.get('category', None)

            if name:
                queryList = queryList.filter(name = str(name))
            if category:
                queryList = queryList.filter(category = str(category))
            
            return queryList

def getname(request):
    if request.method == "GET" and request.is_ajax():
        name = Restaurant.objects.exclude(name__isnull=True).\
            exclude(name__exact='').order_by('name').values_list('name').distinct()
        name = [i[0] for i in list(name)]
        data = {
            "name": name, 
        }
        return JsonResponse(data, status = 200)

def getcategory(request):
    if request.method == "GET" and request.is_ajax():
        category = Restaurant.objects.exclude(category__isnull=True).\
            exclude(category__exact='').order_by('category').values_list('category').distinct()
        category = [i[0] for i in list(category)]
        data = {
            "category": category, 
        }
        return JsonResponse(data, status = 200)

def map(request, area):
    return util_render(request, 'restaurants/map.html')

# Render about view
def about(request):
    return util_render(request, 'restaurants/about.html')

# Contact view
# Render template if provided through GET request
# Attempts to send contact information email if provided through POST request
def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)

        if form.is_valid():

            name          = form.cleaned_data['name']
            from_email    = form.cleaned_data['from_email']
            subject       = form.cleaned_data['subject']
            message       = form.cleaned_data['message']

            subject_email_campus  = "Contact Form Submission: %s - %s" % (name, subject)
            subject_email_confirm = "Thank you for your submission"

            status = send_contact_email(subject_email_campus,
                                        message,
                                        "restaurants/contact_campus.txt",
                                        settings.CONTACT_EMAIL_ADDRESS,
                                        [settings.CONTACT_EMAIL_ADDRESS],
                                        headers = {
                                            "Reply-To": from_email
                                        })

            status &= send_contact_email(subject_email_confirm,
                                         message,
                                         "restaurants/contact_confirm.txt",
                                         settings.CONTACT_EMAIL_ADDRESS,
                                         [from_email])

            if status == False:
                return HttpResponse("Invalid header found")

    return util_render(request, 'restaurants/contact.html', {'form': form})

# Subscribe view
def subscribe(request):
    if request.method == "POST":
        email = request.POST["email_id"]

        send_sub_mail = SendSubscribeMail(email)

        # Send the email
        # Status is True when subscription is successful,
        # False when unsuccessful (email already added to Mailchimp)
        status = send_sub_mail.run()

        if status:
            # Subscription successful 
            return HttpResponse("/")
        else:
            # Subscription failed
            data = {"status": "404"}
            return JsonResponse(data)

def food(request, area, name):
    Restaurant_food_list = Restaurant_Foods.objects.filter(area=area).filter(name=name)
    context = {
        'restaurant_food_list': Restaurant_food_list
    }
    return util_render(request, 'restaurants/food.html', context)

campusnutrition/apps/restaurants/templates/restaurants/about.html
{% extends "restaurants/base.html" %} {% load static %} {% load file_exists %}
{% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'restaurants/css/about.css' %}"
/>

<div class="feedback-header-container">
  <div class="feedback-header-title">ABOUT US</div>
</div>

<div id="LandingPagesApp">
  <div data-reactroot="">
    <div class="sc-jKJlTe dQohoe" <div>
      <!-- react-empty: 25 --><!-- react-empty: 26 -->
      <div class="sc-epnACN bDNNbo sc-EHOje dNDakg" size="96">
        <section class="sc-dfVpRl hKOiml sc-rBLzX dFoZcU" size="16">
          <div class="sc-EHOje jyUtsF" size="24">
            <p
              class="sc-gzOgki kVoFCk sc-ktHwxA dHDaJd"
              size="20"
              color="#999999"
              font-family="DD-TTNorms"
            >
              Campus Nutrition is an independent non-profit organization committed to improving campus health and students’ diets. Its aim is to address and minimize current barriers that prevent people from consuming a healthy diet through advocacy, awareness, and education about nutrition. Campus Nutrition is not affiliated with UBC.
            </p>
          </div>
        </section>
        <div class="sc-cIShpX hnHKIv">
          <div class="sc-EHOje gYaqtj" size="64">
            <h1
              class="sc-jtRfpW cBAdir sc-hEsumM lvpnK"
              size="44"
              color="#191919"
            >
              Nutritional Transparency Initiative for Students
            </h1>
            <div>
              <div class="sc-kafWEX hbnwNv">
                <img src="{% static 'restaurants/images/salad-healthy-diet-spinach.jpg' %}" style="border-radius: 10px; height: auto; width: 60%;">
                <div class="sc-feJyhm ikcnVI sc-bZQynM enlVCR" size="32">
                  <div class="sc-iELTvK cYkntd sc-EHOje lddRnt" size="16">
                    <h2
                      class="sc-btzYZH jQLBQF sc-bMvGRv dkjDds"
                      size="32"
                      color="#77B7C4"
                    >
                      INSERT_TITLE
                    </h2>
                    <p
                      class="sc-lhVmIH cLyyIP sc-ktHwxA dHDaJd"
                      size="20"
                      color="#999999"
                      font-family="DD-TTNorms"
                    >
                    Campus Nutrition is an independent non-profit organization committed to improving campus health and students’ diets. Its aim is to address and minimize current barriers that prevent people from consuming a healthy diet through advocacy, awareness, and education about nutrition. Campus Nutrition is not affiliated with UBC.

                    </p>
                    <div
                      class="sc-bYSBpT llMffr sc-CtfFt eiUpeN"
                      size="20"
                      color="#77B7C4"
                    >
                    </div>
                  </div>
                </div>
              </div>
              <div class="sc-kafWEX kxdrwC">
                  <img src="{% static 'restaurants/images/pexels-photo.jpg' %}" style="border-radius: 10px; height: auto; width: 60%;">
                <div class="sc-feJyhm ikcnVI sc-bZQynM enlVCR" size="32">
                  <div class="sc-iELTvK cYkntd sc-EHOje lddRnt" size="16">
                    <h2
                      class="sc-btzYZH jQLBQF sc-bMvGRv iypFeX"
                      size="32"
                      color="#3A646E"
                    >
                      INSERT_TITLE
                    </h2>
                    <p
                      class="sc-lhVmIH cLyyIP sc-ktHwxA dHDaJd"
                      size="20"
                      color="#999999"
                      font-family="DD-TTNorms"
                    >
                    Campus Nutrition is an independent non-profit organization committed to improving campus health and students’ diets. Its aim is to address and minimize current barriers that prevent people from consuming a healthy diet through advocacy, awareness, and education about nutrition. Campus Nutrition is not affiliated with UBC.
                  </p>
                    <div
                      class="sc-bYSBpT llMffr sc-CtfFt frEeEL"
                      size="20"
                      color="#3A646E"
                    >
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endblock %}
      </div>
    </div>
  </div>
</div>

campusnutrition/apps/restaurants/templates/restaurants/base.html
{% load static %} {% load file_exists %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ tracking_id }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', "{{ tracking_id }}");
    </script>
      
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, inital-scale=1.0" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'restaurants/css/base.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="shortcut icon"
      href="{% static 'restaurants/images/favicon.ico' %}"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="{% static 'restaurants/js/subscribe.js' %}"></script>

    <title>{% block title %}{% endblock %}</title>

    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <div id="root">
      <header>
        <div class="navbar-fixed">
          <nav class="nav-wrapper z-depth-0">
            <div class="container">
              <a href="/" class="brand-logo">
                <img
                  src="{% static 'restaurants/images/campus_nutrition_logo_header.png' %}"
                  alt="Campus Nutrition Logo"
                  class="logo-image"
                />
              </a>
              <a href="" class="sidenav-trigger" data-target="mobile-menu">
                <i class="material-icons">menu</i>
              </a>
              <ul class="right hide-on-med-and-down">
                <li><a href="/">Home</a></li>
                <li><a href="map">Map</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
              </ul>
              <ui id="mobile-menu" class="sidenav grey lighten-2">
                <li><a href="/">Home</a></li>
                <li><a href="map">Map</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
              </ui>
            </div>
          </nav>
        </div>
        {% block search %}{% endblock %}
      </header>

      {% block content %}{% endblock %}

      <footer class="site-footer">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-6">
              <h6>About</h6>
              <p class="text-justify">
                Campus Nutrition is an independent non-profit organization
                commited to increasing awareness about nutrition and the food
                options that are available on campus. It aims to address and
                minimize current barriers that prevent students and other
                members of campus communties from consuming a healthy diet.
                Campus Nutrition was founded in 2019 by a group of UBC students.
              </p>
            </div>

            <div class="quick-links col-xs-6 col-md-3">
              <h6>Quick Links</h6>
              <ul class="footer-links">
                <li><a href="/about">About Us</a></li>
                <li>
                  <a href="/why">Why Campus Nutrition</a>
                </li>
                <li><a href="/contact">Contact Us</a></li>
              </ul>
            </div>

            <div class="col-xs-6 col-md-3">
              <h6>Join</h6>
              <div class="join-us-container">
                <div class="join-us">
                  Join our email list to stay up to date with the latest from
                  Campus Nutrition!
                </div>
                <div class="success-message" style="display: none">
                  Success!
                </div>
                <form
                  class="footer-input-form"
                  id="subscribe"
                  form
                  method="POST"
                >
                  {% csrf_token %}
                  <div class="footer-email-input-container">
                    <input
                      class="footer-email-input"
                      placeholder="Enter your email address"
                      id="email_id"
                      name="email_id"
                      type="email"
                      required
                    />
                    <button
                      class="footer-email-submit"
                      type="submit"
                      value="Subscribe"
                      id="email_submit"
                    >
                      <i class="material-icons icon-white">arrow_right_alt</i>
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <hr />
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
              <p class="copyright-text">
                Copyright &copy; 2020 All Rights Reserved by Campus Nutrition.
              </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
              <ul class="social-icons">
                <li>
                  <a class="email" href="mailto:admin@campusnutrition.ca"
                    ><i class="fa fa-envelope"></i
                  ></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

{% block extra_js %}{% endblock %}

<script>
  $(document).ready(function() {
    $(".sidenav").sidenav();
  });

  $(".footer-input-form").submit(function() {
    $(".success-message").show();
    return false;
  });

  $("#subscribe").submit(function(e) {
    e.preventDefault();
    var email_id = $("#email_id").val();
    if (email_id) {
      var csrfmiddlewaretoken = csrftoken;
      var email_data = {
        email_id: email_id,
        csrfmiddlewaretoken: csrfmiddlewaretoken
      };
      $.ajax({
        type: "POST",
        url: "/subscribe/",
        data: email_data,
        success: function(response) {
          $("#email_id").val("");
          if (response.status == "404") {
            alert("This Email is already been subscribed!");
          }
        },
        error: function(response) {
          alert("Sorry Something went Wrong");
          $("#email_id").val("");
        }
      });
      return false;
    } else {
      alert("Please provide correct email!");
    }
  });

  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== "") {
      var cookies = document.cookie.split(";");
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i]);
        if (cookie.substring(0, name.length + 1) === name + "=") {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

  function csrfSafeMethod(method) {
    return /^(GET|HEAD|OPTIONS|TRACE)$/.test(method);
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
</script>

campusnutrition/apps/restaurants/templates/restaurants/contact.html
{% extends "restaurants/base.html" %} {% load static %} {% load file_exists %}
{% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'restaurants/css/contact.css' %}"
/>

<div class="feedback-header-container">
  <div class="feedback-header-title">CONTACT US</div>
  <div class="additional-contact-info">
    Questions? Suggestions? Interested in getting involved? We’d love to hear from you! Please fill out the form to contact us and we’ll respond to you shortly.
  </div>
</div>

<div class="contact-form-container">
  <img
    src="{% static 'restaurants/images/contact_us.jpeg' %}"
    alt="Campus Nutrition logo"
  />
  <form method="post" class="feedback-form" action="/contact/">
    {% csrf_token %}
    {{ form.ad_p }}
    <div class="input-container">
      <div class="form-group field">
        <input
          type="text"
          class="form-field"
          placeholder="Name"
          name="name"
          id="id_name"
          required
        />
        <label for="id_name" class="form-label">Name</label>
      </div>
      <div class="form-group field">
        <input
          type="email"
          class="form-field"
          placeholder="Email"
          name="from_email"
          id="id_from_email"
          required
        />
        <label for="id_from_email" class="form-label">Email</label>
      </div>
      <div class="form-group field">
        <input
          type="text"
          class="form-field"
          placeholder="Subject"
          name="subject"
          id="id_subject"
          required
        />
        <label for="id_subject" class="form-label">Subject</label>
      </div>
    </div>
    <div class="textarea-container">
        <textarea
            name="message"
            class="feedback-input"
            placeholder="Comment"
            id="id_message"
            required
        ></textarea>
        <label for="id_message"></label>
    </div>

    <input class="contact-submit" type="submit" value="SUBMIT" />
  </form>
</div>

{% endblock %}

campusnutrition/apps/restaurants/templates/restaurants/food.html
{% extends 'restaurants/base.html' %} {% load static %} {% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'restaurants/css/food.css' %}"
/>

<script>
$(document).ready(function(){
  		$('.modal').modal();
 });

 var modal = document.getElementsByClassName('modal');
 for(var i = 0; i < modal.length; i++) {
  var modal_id = modal[i].id;
  $(document).ready(function(modal_id){
  		$(modal_id).modal();
 });

 }

</script>


<main class="page">
  {% if restaurant_food_list %}
  <div class="restaurants-list">
    {% for food in restaurant_food_list %}
      <div class="content">
        <div class="card">
          <img src="https://cdn.pixabay.com/photo/2013/07/12/16/53/burger-151421_960_720.png" alt="Burger" class="image">
          <div class="infos">
              <h2 class="title">{{ food.food }}<span class="food_icon"></span></h2>
              <h3 class="calorie">Calories: {{ food.calories }}</h3>
              <h3 class="restriction">{{ food.category }}</h3>
              <p class="txt">{{ food.info2 }}</p>
            <h3>{{ food.info2 }}</h3>
            <h3>click for popup of detail food info</h3>
          </div>
          <a href="#modal{{forloop.counter}}" class="modal-trigger __child-anchor"></a>
        </div>
      </div>
    {% endfor %}
  </div>
  {% endif %}

  {% if restaurant_food_list %}
  {% for food in restaurant_food_list %}
  <div id="modal{{forloop.counter}}" class="modal">
    <div class="modal-content">
      <h4>Modal Header {{forloop.counter}}</h4>
      <p>{{ food.modal_Info }}</p>
    </div>
  </div>
  {% endfor %}
  {% endif %}
  
</main>

{% endblock content %}

campusnutrition/apps/restaurants/templates/restaurants/home.html
{% extends "restaurants/base.html" %}
{% load static %}
{% load file_exists %}


{% block search %}
<div class="area-image-container">
    <img
        src="{% static 'restaurants/images/areas/ubc.jpg' %}"
        alt="ubc image"
        class="area-image"
    >
    <div class="area-image-text">Places to eat at UBC Vancouver</div>
</div>
{% endblock %}

{% block content %}

{% url 'get_names' %}
{% url 'get_categories' %}
{% url 'listing' %}


<div id="list-data" url="{% url 'listing'%}">list data</div>
<div id="no-result">
    <h1>No results found</h1>
</div>

<main class="page">
    
    <br>
    <label for="name">Choose a name:</label>
    <select id="name" url = "{%url 'get_names' %}" style="display: block;">
    </select>

    <label for="category">Country</label>
    <select id="category" url = "{%url 'get_categories' %}" style="display: block;">
    </select>

    <div class="content">
        <div class="search-container">
            <div class="search-icon-container">
                <i class="material-icons">search</i>
            </div>
            <div class="search-dropdown">
                <span>Restaurant</span>
                <div class="search-dropdown-content">
                <div class="search-dropdown-item">Restaurant</div>
                <div class="search-dropdown-item">Category</div>
                </div>
            </div>
            <div class="dropdown-icon-container">
                <i class="material-icons">arrow_drop_down</i>
            </div>
            <input type="search" class="search-query" placeholder="Search Restaurants">
            <div class="refresh-icon-container">
                <i class="material-icons">refresh</i>
            </div>
        </div>
        {% if restaurant_list %}
            <div class="restaurants-list" id="rest-list">
                {% for restaurant in restaurant_list %}
                    <div class="restaurant-card">
                        <div class="restaurant-card-img-container">
                            <img
                                src="{% static 'restaurants/images/stores/' %}{{ restaurant.img }}" 
                                alt="{{ restaurant.name }}"
                                class="restaurant-card-img"
                            />
                        </div>
                        <h2 class="restaurant-card-title">{{ restaurant.name }}</h2>
                        <div class="restaurant-card-categories">
                            {{ restaurant.category }}
                        </div>
                    </div>
                {% endfor %}
            <div>
        {% endif %}
    </div>
    <script src="{% static 'restaurants/js/filter.js' %}" type="text/javascript"></script>
</main>
{% endblock %}

campusnutrition/apps/restaurants/templates/restaurants/map.html
{% extends 'restaurants/base.html' %} {% load static %} {% block content %}

<head>
  <style>
    /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
    #map {
      height: 800px;
      width: 100%;  /* The width is the width of the web page */
    }
  </style>
</head>
<body>
  <!--The div element for the map -->
  <div id="map"></div>
  <script>
    var map;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: new google.maps.LatLng(49.2606,-123.2460),
        mapTypeId: 'roadmap'
      });

      var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
      let markers = [];

      $.getJSON("/ubc/map/getJSON", function(data) {
        console.log('getjson')
        $.each(data, function(index, value) {
          var marker = new google.maps.Marker({
              position: new google.maps.LatLng(value['lat'], value['lng']),
              label: labels[index % labels.length]
            });

          var infowindow = new google.maps.InfoWindow({
            content: value['address']
          });
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });
          markers.push(marker);
        });
        console.log("pushed markers")
      var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
      });
    }
  </script>
  <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
  </script>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZczE3AoOQTbqeYBt9sfJWdmGpaOsSVkk&callback=initMap">
  </script>

</body>

{% endblock content %}